version: 2

sources:
  - name: nba_api
    loader: SQLite CLI
    schema: main  # SQLite default schema (main)
    description: "Raw NBA data sourced from the NBA API"
    tables:
      - name: player_game_stats
        description: "Player game statistics sourced from the NBA API"
      - name: player_info 
        description: "Player information sourced from the NBA API"

