CREATE TABLE IF NOT EXISTS player_game_stats (
    season_id TEXT,
    player_id INTEGER,
    game_id INTEGER,
    game_date TEXT,
    matchup TEXT,
    wl TEXT,
    min INTEGER,
    fgm INTEGER,
    fga INTEGER,
    fg_pct REAL,
    fg3m INTEGER,
    fg3a INTEGER,
    fg3_pct REAL,
    ftm INTEGER,
    fta INTEGER,
    ft_pct REAL,
    oreb INTEGER,
    dreb INTEGER,
    reb INTEGER,
    ast INTEGER,
    stl INTEGER,
    blk INTEGER,
    tov INTEGER,
    pf INTEGER,
    pts INTEGER,
    plus_minus INTEGER,
    video_available INTEGER
);

